### ISSUE TITLE
When "Repeat attempts to initialize the voice synthesizer driver" is unchecked, "Number of retries (0 - infinitely)" is still displayed.

### ISSUE THREAD

**Issue by cary-rowen** [grisov/Unmute#11]
step:
1. Uncheck "Repeat attempts to initialize the voice synthesizer driver" in the add-on settings dialog.
2. Click the OK button.
3. Open the add-on settings dialog again, You will find "Number of retries (0-infinitely)" is displayed.

In addition, my suggestion is to decompose the functions of adjusting the main volume of the device and controlling the volume of the running application into another add-on.
This makes the name "Unmute" more well-deserved, It is also easy to add more useful functions if you create a new audio control plug-in

**Comment by grisov** [comment]
Hello Cary,
Thank you for the detailed description of the error!
I fixed this, now the next option is hidden dynamically.

Fixed dynamic hiding of spin - 04b741bc91615c80166 .

The release has also been updated:
https://github.com/grisov/Unmute/releases/tag/v1.3

As for the division of the addon into two different ones, I think it is inexpedient in this moment for the following reasons:

1. Technical:
Currently all functions of the add-on use one module - pycaw.
This module is not yet perfect and there are reviews on the network about the errors generated by it.
On the other hand, if we divide Unmute into several different add-ons.
They will all use the same dependencies, and install them in NVDA each separately.
And we will get many instances of the same module in different add-ons.
This is not critical, but in my humble opinion, it is not a efficient use of resources.
At this moment - all the features of the pycaw module are implemented in one add-on.

2. So far the Unmute add-on is extremely simple and performs only a few functions...
A little later I will try to add volume control for additional audio devices.
But for now, these are all the functions that the add-on performs.

These are just my opinions, and if other users will support the idea of division the add-on - there is no problem to do so.
Thanks again for your participation in the project and feedback!
Oleksandr
