### ISSUE TITLE
The startup sound of the add-on always plays

### ISSUE THREAD

**Issue by Lo-lo78** [grisov/Unmute#17]
Hi Oleksandr,
nothing really serious; I wanted to point out that the add-on startup sound always plays even if the NVDA volume is online.
It would be nice if it only played when NVDA is below the volume set in NVDA's settings.
Right now, when I launch NVDA, there is both classic screen reader audio and add-on audio activation audio.
Regards!

**Comment by grisov** [comment]
Hi Manolo,
Thank you for your help in testing the add-ons!
Most likely, the add-on switches the output to the main audio device every time when NVDA starts.
This occurs when the audio output device is in the NVDA settings is differ from the default output device or "Microsoft Sound Mapper".

This can be easily solved in one of the following ways:

1. After restarting NVDA, just save the current configuration using NVDA+Ctrl+C.
The default audio device will be saved in the NVDA settings and switching will not occur each time when NVDA starts.

2. If you don't want to change the NVDA configuration - just disable the function of switching audio devices in the Unmute settings panel.

I can turn off signal playback after switching devices, but the add-on will still switch the output every time NVDA starts.

I just had the idea to allow the user to choose the audio device to which the output will switch at startup.
Just displaying the list of choices of available audio output devices in the add-on settings panel.

**Comment by Lo-lo78** [comment]
Yes, the checkbox is deactivated: Switch to the default audio output 
device, it works perfectly! Sorry, this is not a useful tip! I was 
wrong! Thank you for what you do

Il 21/11/2020 17:20, Oleksandr Gryshchenko ha scritto:

**Comment by grisov** [comment]
Dear friend,
I am very grateful to you for your interest and your always very relevant feedbacks!
I consulted with another user and decided that the list of choices with output audio devices should not be added to the settings panel as this will duplicate the existing standard NVDA feature.
Be safety!
Oleksandr
