### ISSUE TITLE
I can't config this add-on to make it work

### ISSUE THREAD

**Issue by manhcuong0312** [grisov/Unmute#20]
Hello  
Today, I try using this add-on to fix translation errors if any, but after install, I didn't see Unmute settings dialog. Take a look at documentation, I didn't see how to open that dialog. I tried unmuting my system volume, then start NVDA, but no affect.  

1. Please help me if I did something wrong.
2. Consider add a small part on how to open add-on settings dialog in your documentation.

I Use Windows 10 professional 64 bit, version 20h2, NVDA 2020.3. This problem occurs with both version of this add-on, one I generated myself from its repo, one I downloaded from the given URL in the documentation.  
So sorry because I didn't try this add-on before deciding to translate.

**Comment by grisov** [comment]
Hello Dang,
Currently, the settings panels of all add-ons are added to the general NVDA settings dialog.
So I didn't mention it in ReadMe, but you're right - I should do it.

To open the add-on settings panel, follow these steps:
1. Press NVDA+N to open NVDA menu.
2. Then go to "Preferences" -> "Settings..." and in the categories list find and open "Unmute Windows Audio".
That's it, you can now use the Tab key to move between add-on settings.

If there is no "Unmute Windows Audio" section in the categories list.
Then please check the NVDA log for errors.
1. Press NVDA+N to open NVDA menu.
2. Go to "Tools" submenu and then - "View log".
If there are words "Error" or "Traceback" in the log - please send it to me for analysis.
Thank you and good luck!

**Comment by grisov** [comment]
ReadMe and release updated.

**Comment by manhcuong0312** [comment]
Hi @grisov   
It worked on my personal laptop. Before, I tried this on a desktop at my office so I'll check it tomorrow and send you the log file if the error still occur.  
Thank you so much.

**Comment by manhcuong0312** [comment]
Hi @grisov  
The add-on worked on the desktop at my office. Today, I checked in NVDA/add-on folder, and I see a folder name somethign like unmute - pending install. I remove, and reinstall the add-on, and it work so I think we could close this issue.  
Thanks for adding a short guide on how to open add-on settings.  
Cuong
