### ISSUE TITLE
The initial volume is too high, if wearing headphones will cause harm to the user

### ISSUE THREAD

**Issue by cary-rowen** [grisov/Unmute#7]
1. Set custom volume level, The default value of 90 is too noisy, especially when wearing headphones.
Increase the volume if it is lower than:
The default value here also needs to be adjusted smaller, for the same reason as above. I usually wear headphones and the system volume is set to 15. In this case, I will be stunned by the default value of the add-on.

**Comment by grisov** [comment]
Hello
I corrected the default volume levels - 8b4858d2eba73419e2a0d .

The add-on release has been updated to reflect these changes:
https://github.com/grisov/Unmute/releases/download/v1.3/unmute-1.3.nvda-addon

Good luck!
